version: '3'
services:
  ros_humble:
    container_name: ubuntu_ros_robot
    environment:
      - username=Mir_robot
    build:
      context: ./mir_data_collection
      dockerfile: DockerFile
    tty: true