services:
  postgres:
    image: postgres:latest
    environment:
      #POSTGRES_USER:
      #POSTGRES_PASSWORD:
      POSTGRES_DB: ros_db
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
      - "5432:5432"
    volumes:
      - ./cloud/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eti

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./cloud/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - eti

  mqtt_broker:
    image: eclipse-mosquitto:1.6.12
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - eti

  cloud:
    build: ./cloud
    networks:
      - eti
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

networks:
  eti:
    driver: bridge
