FROM osrf/ros:humble-desktop-full

ARG USERNAME=Mir_robot
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3-pip
ENV SHELL /bin/bash

#Anything else
RUN sudo apt update -y
RUN sudo apt upgrade -y
RUN sudo apt install ros-dev-tools -y

#Set up mir_robot package
RUN mkdir -p ~/ros2_ws/src
RUN cd ~/ros2_ws/
RUN git clone -b humble-devel https://github.com/relffok/mir_robot src/mir_robot
RUN vcs import < src/mir_robot/ros2.repos src --recursive

RUN sudo apt update
RUN sudo apt install -y python3-rosdep
RUN rosdep update
RUN rosdep update --rosdistro=humble
RUN rosdep install --from-paths src --ignore-src -r -y --rosdistro humble

RUN source /opt/ros/humble/setup.bash
RUN cd ~/ros2_ws
RUN colcon build

RUN echo "source ~/ros2_ws/install/setup.bash" >> ~/.bashrc

RUN cd ~/ros2_ws/src/mir_data_collection/mir_data_collection
RUN start_data_collection.s

